name: Lint fs-client with Ruff

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # You can specify any version you need

    - name: Install dependencies
      run: |
        pip install --upgrade pip  # Upgrade pip to the latest version
        pip install ruff  # Install ruff-lint

    - name: Run Ruff Lint
      run: |
        ruff check fs-client/ --config /file-server/fs-client.pyproject.toml # Run ruff lint on the fs-client directory